extends Node


signal grabbable_placed
signal customer_left
signal day_started
signal day_ended
signal upgrade_purchased
signal life_lost
signal player_lost
signal sidescrolled_left
signal sidescrolled_right
signal boss_fight_started
signal charon_on_screen_timer_ended
signal charon_off_screen_timer_ended
signal charon_started
signal charon_customer_created
